version: '3'
name: paltable-dev
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: bash -c "npm start"